### ISSUE TITLE
3.1 Write SIR intro/demo

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#12]

**Comment by MObrien-IDM** [comment]
Most participants should be familiar with SIR models in general, so this can be focused on the simple ABM we are using. I think it'll be most helpful to walk through the defining people and simulation segments (maybe some note about where this code comes from) and then have the participants make sure they can run the basic version of the model.

**Comment by cliffckerr** [comment]
Will do a live demo, but backup slides are here:
https://docs.google.com/presentation/d/14gAftZ4hmMb7sed4fwUWVQMFTmnUOdHF/edit#slide=id.g26aff56dda6_0_129
