### ISSUE TITLE
3.4 Write interaction and transmission lecture/tutorial

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#4]
https://docs.google.com/spreadsheets/d/1F2TB7w_devnUSly1ne69HJDo_Cx1vOJU/edit#gid=755125898

**Comment by MObrien-IDM** [comment]
I think we changed the names so that this one is actually 3.4 and if that's the case, I think you can do the expansion of simple model to add the network.

**Comment by cliffckerr** [comment]
Closed by #26
