### ISSUE TITLE
4.2 Write calibration tutorial

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#5]
https://docs.google.com/presentation/d/1mZrCLxdG8EjKN_22pDrQ3zquo13vBsh5YAF7VHx6C14/edit#slide=id.p

See also: https://docs.google.com/presentation/d/1-39wjtxzWP4uwE80k6UujxEU7dCrKoZM/edit#slide=id.p34

**Comment by emilydriano** [comment]
For the tutorial, could be cool to see:

- implementation of basic Calibration class (how it's structured, what params are needed, etc)
- what data is needed/where it's stored to validate the model
- run of a simple calibration script with plot to show difference between model results vs data (to highlight the need for free params)
- run of a calibration script with at least one free parameter to talk through process of fine-tuning based on results of many different sims

**Comment by cliffckerr** [comment]
Done
