### ISSUE TITLE
3.4 Help with agent interactions lecture/tutorial

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#7]
https://docs.google.com/presentation/d/12hNocuCtktqwUIFs1jrR8mPPZaZc33SR/edit#slide=id.g26aff56dda6_0_129

**Comment by emilydriano** [comment]
some ideas here...could have a tutorial that iteratively adds the following:
- defining agents and their attributes
- designing interaction rules based on model's objectives/system dynamics
- implementing agent interactions (perhaps firstly with oneself; i.e. storing memory of experiences like vaccination history, then interactions with other agents/env) - helpful to show which files are modified to implement this
- visualization/animation to show the interaction

**Comment by MObrien-IDM** [comment]
Is this actually for 3.4?

**Comment by emilydriano** [comment]
> Is this actually for 3.4?

good catch @MObrien-IDM -  I would assume so & that it would be more specific to transmission interactions

**Comment by MObrien-IDM** [comment]
I think the 2.3 lecture materials look pretty good - I would suggest closing this out and replacing with a 3.4 if not already created

**Comment by cliffckerr** [comment]
Yes, can close -- thanks both!
