### ISSUE TITLE
3.3 Parameterization tutorial

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#8]

**Comment by MObrien-IDM** [comment]
At the end of the lecture, they've already done exercises to draw up a conceptual flow chart, and then this is the last small group exercise: 

Small groups

Choose one key event from one of your flowcharts. 
Decide on one parameter that will inform the event

Write pseudo code (optional: Python!) defining your parameter

The tutorial can give them some space to write real code for this and add their parameter (even if it's not completely relevant) to the SIR model.

**Comment by cliffckerr** [comment]
Closed by #26
