### ISSUE TITLE
5.2 Designing and implementing interventions

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim_training#9]
Start with SIR, do beta change, then build up from there. See 7.1

Or: thinking through delivery platforms, etc.

**Comment by MObrien-IDM** [comment]
The other option here is to get some real data involved. We'll have already gone through data integration.

**Comment by MObrien-IDM** [comment]
Ideas from looing over the lecture: 

Participants define:

- Who is impacted by the intervention
- What is the magnitude of impact
- How does impact change over time

Participants get instructions from lecture for model integration:

- Create a class for interventions
- Determine what values are needed to initialize a specific intervention
- Determine which agent and/or sim values need to change in the intervention
- Create function(s) to modify these changing params accordingly
- Create a function in the Simulation class that applies the intervention(s)
-

**Comment by MObrien-IDM** [comment]
Also @cliffckerr if you take a look at the lecture there are some covasim materials that you should review and determine if you want to keep them in.

**Comment by cliffckerr** [comment]
Closed by #26
